### ISSUE TITLE
ZJIT: Ractor test skipped for YJIT/ZJIT hangs if re-enabled

### ISSUE THREAD

**Issue by k0kubun** [Shopify/ruby#618]
This test (test_ractor.rb:388 as of Aug 6th, 2025) in `bootstraptest/test_ractor.rb` never finishes with `--zjit-call-threshold=1`:

```
assert_equal '{ok: 3}', %q{
  Ractor.new Ractor.current do |main|
    q = Thread::Queue.new
    Thread.new do
      q << true
      loop{}
    ensure
      main << :ok
    end
    Thread.new do
      q << true
      while true
      end
    ensure
      main << :ok
    end
    Thread.new do
      q << true
      sleep 1
    ensure
      main << :ok
    end
    # wait for the start of all threads
    3.times{q.pop}
  end
  3.times.map{Ractor.receive}.tally
}
```

**Comment by XrXr** [comment]
We've been running all btests for a long time so I believe this was fixed.

**Comment by k0kubun** [comment]
> We've been running all btests for a long time

No, we haven't. This test is skipped when `zjit_enabled?`, like `yjit_enabled?`. Until we drop the skip, this issue should be kept open. Note that we also don't run `bootstraptest/test_yjit.rb` either (because it still fails).

**Comment by st0012** [comment]
For ZJIT it's not hanging anymore so I opened https://github.com/ruby/ruby/pull/14421 to update the condition.
